HakiAxians/StudentManagementSystem

Pages/Course.page.al, Pages/Registration.page.al, Pages/Student.page.al, Tables/Course.Table.al, Tables/Registration.Table.al, Tables/Student.Table.al
=> 3 tabaelat e para

Pages/Grade.Page.al, Pages/Payment.Page.al, Pages/Professor.Page.al, Tables/Grade.Table.al
Added pages: Grade, Payment and Professor
=> Added pages: Grade, Payment and Professor

CodeUnits/StudentRegistration.al
added Codeunit in StudentRegistration
=> added Codeunit in StudentRegistration

Pages/Grade.Page.al, Pages/Payment.Page.al, Pages/Registration.page.al, Query/GradeDistribution.Query.al, Query/StudentEnrollment.Query.al, Tables/Grade.Table.al
Added querys and fixed some stuff
=> Added querys and fixed some stuff

CodeUnits/StudentAverage.al, Pages/Cards/Professor.Page.al, Pages/Lists/Grade.page2.al, Pages/Lists/Payment.Page2.al, Pages/Lists/Professor.Page2.al
=> added actions

.gitignore, .vscode/launch.json, CodeUnits/StudentAverage.al, Pages/Cards/Professor.Page.al, Pages/Cards/Student.page.al, ProfessorReport.rdlc, Reports/Professor.Report.al, Reports/Student.Report.al, StudentReport.rdlc
=> Added new reports

CodeUnits/GradeEmail.CodeUnit.al, CourseReport.rdlc, Pages/Cards/Course.page.al, Pages/Cards/Grade.Page.al, Pages/Cards/Professor.Page.al, Pages/Cards/Registration.page.al, Pages/Cards/Student.page.al, Reports/Course.Report.al, Tables/Course.Table.al, Tables/Grade.Table.al, Tables/Registration.Table.al, Tables/Student.Table.al
Added CourseReport and made some changes
=> Added CourseReport and made some changes

CourseReport.rdlc, Pages/Cards/Student.page.al, Pages/Lists/Student.Page2.al, Tables/Student.Table.al
=> Some changes

CourseReport.rdlc, Pages/Cards/Student.page.al, Pages/Lists/Student.Page2.al, Tables/MeetingScheduler/MeetingCalendar.page.al, Tables/MeetingScheduler/MeetingScheduler.page.list.al, Tables/MeetingScheduler/MeetingScheduler.table.al
=> many many positive updates

Pages/Cards/Course.page.al, Pages/Cards/Grade.Page.al, Pages/Cards/Payment.Page.al, Pages/Cards/Professor.Page.al, Pages/Cards/Registration.page.al, Pages/Cards/Student.page.al, Pages/Lists/Course.page2.al, Pages/Lists/Payment.Page2.al, Pages/Lists/Professor.Page2.al, Pages/Lists/Registration.Page2.al, Pages/Lists/Student.Page2.al
=> addding stuff

CodeUnits/GradeEmail.CodeUnit.al, CodeUnits/ImportExel.CodeUnit.al, Pages/Cards/Grade.Page.al, Pages/Cards/Student.page.al, Tables/Student.Table.al
Added Import CodeUnit and chaget somethings
=> Added Import CodeUnit and chaget somethings

Enums/PaymentStatus.Enum.al, Pages/Lists/Course.page2.al, Pages/Lists/Grade.page2.al, Pages/Lists/Payment.Page2.al, Pages/Lists/Professor.Page2.al, Pages/Lists/Registration.Page2.al, Pages/Lists/Student.Page2.al, Tables/Registration.Table.al
New related buttons and registration page updated
=> New related buttons and registration page updated

CodeUnits/StudentAverage.al, Pages/BusinessChartPart.Page.al, Pages/Cards/Student.page.al, Tables/Grade.Table.al, Tables/Student.Table.al
=> minor changes

Pages/Cards/Course.page.al, Pages/Cards/Grade.Page.al, Pages/Cards/Payment.Page.al, Pages/Cards/Professor.Page.al, Pages/Cards/Registration.page.al, Pages/Cards/Student.page.al
Updated from Action properties(Promoted) to Area Promoted
=> Updated from Action properties(Promoted) to Area Promoted

Pages/Cards/Student.page.al
=> actions neww

PageExtensions/Headline.PageExtensios.al
=> New headline

CodeUnits/StudentCourseAnalysis.CodeUnit.al, Pages/Cards/Payment.Page.al, Pages/Cards/Registration.page.al, Pages/Cards/Student.page.al, Query/StudentEnrollment.Query.al, Tables/Course.Table.al, Tables/Payment.Table.al, Tables/Student.Table.al
New codeunit and minor changes
=> New codeunit and minor changes

PageExtensions/Activities.PageExtension.al, Pages/BusinessChartPart.Page.al, Pages/Lists/Student.Page2.al, Pages/RollCenter.Page.al
=> Role Center

Pages/Role Center/Headline.Page.al, Tables/Student.Table.al
=> small changes

CodeUnits/CourseAssigmentLogger.al, CodeUnits/CourseManagment.al, Pages/Cards/Registration.page.al, Tables/Registration.Table.al
=> New event sub
